#!/usr/bin/env python3
"""Regenerate the driver-validation page's STATUS TABLE + COUNTS from the single source of truth —
`SkansCP --driver-validation` (ValidationMatrixSvc joined with the validation ledger, the same code the
console renders) — and LINT the curated evidence section so no prose line can claim a proven status the
ledger does not back. This is how the page stays honest: a cell (or an evidence claim) can only be green
when an executed test wrote it to the ledger; nobody can hand-type a green ahead of the proof.

Run after each validation pass, then deploy:
    SKANS_WINRM_PASS=... python3 tools/sync-driver-validation.py && ./deploy.sh

Only the region between the AUTOGEN markers is machine-written; the frontmatter, intro, ladder note, the
"## Validated so far — evidence" bullets, and "## Next" stay hand-curated. Secrets are never committed:
the appliance WinRM password is read from $SKANS_WINRM_PASS.
"""
import os, sys, re, base64, json, time

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)            # md4shim (pywinrm NTLM shim) sits beside this file
import md4shim, winrm  # noqa: E402

APP  = os.environ.get("SKANS_WINRM_HOST", "192.168.102.92")
USER = os.environ.get("SKANS_WINRM_USER", "Administrator")
PW   = os.environ.get("SKANS_WINRM_PASS")
if not PW:
    sys.exit("set $SKANS_WINRM_PASS (appliance WinRM password) — never committed to the repo")

PAGE  = os.path.join(HERE, "..", "content", "2.0", "reference", "driver-validation.md")
START = "<!-- AUTOGEN:driver-validation — regenerated by tools/sync-driver-validation.py from `SkansCP --driver-validation`; do not hand-edit -->"
END   = "<!-- /AUTOGEN:driver-validation -->"
TIERS = ("hardware", "emulation", "known-issue", "spec")

s = winrm.Session(APP, auth=(USER, PW), transport="ntlm", server_cert_validation="ignore")
def ps(script): return s.run_ps(script).std_out.decode(errors="replace")

def run_verb_and_fetch():
    # `--driver-validation` is a CLI verb that occasionally races the web host and fails to bind :7328 while
    # the console service runs; drive it via a fresh SYSTEM scheduled task and retry until the table appears.
    task = r'''$exe="C:\Skans\controlplane\Skans.ControlPlane.exe";$o="C:\Skans\vt.txt";Remove-Item $o -EA SilentlyContinue
$bat="C:\Skans\vt.bat";Set-Content $bat -Value ('"'+$exe+'" --driver-validation > "'+$o+'" 2>&1') -Encoding Ascii
Unregister-ScheduledTask SkansVT -Confirm:$false -EA SilentlyContinue
$a=New-ScheduledTaskAction -Execute cmd.exe -Argument ('/c "'+$bat+'"')
$pr=New-ScheduledTaskPrincipal -UserId SYSTEM -LogonType ServiceAccount -RunLevel Highest
Register-ScheduledTask -TaskName SkansVT -Action $a -Principal $pr -Force | Out-Null
Start-ScheduledTask SkansVT; Start-Sleep 3
$n=0; while((Get-ScheduledTask SkansVT).State -eq 'Running' -and $n -lt 40){Start-Sleep 2;$n++}
Unregister-ScheduledTask SkansVT -Confirm:$false -EA SilentlyContinue'''
    for _ in range(5):
        ps(task)
        b = ps(r'if(Test-Path C:\Skans\driver-validation.md){[Convert]::ToBase64String([IO.File]::ReadAllBytes("C:\Skans\driver-validation.md"))}else{"MISSING"}').strip()
        if b and b != "MISSING":
            md = base64.b64decode(b).decode("utf-8", "replace")
            if "| Vendor |" in md:
                return md
        time.sleep(3)
    sys.exit("could not generate driver-validation.md from the verb (web-host :7328 race did not clear)")

def fetch_ledger():
    b = ps(r'[Convert]::ToBase64String([IO.File]::ReadAllBytes("C:\Skans\driver-validation-ledger.json"))').strip()
    return json.loads(base64.b64decode(b).decode("utf-8-sig"))

def extract(md):
    lines = md.splitlines()
    tsm = re.search(r'Generated (.+? UTC)', md)
    ts = tsm.group(1) if tsm else "the latest test pass"
    counts = next((l for l in lines if l.startswith("**Cert-deploy (")), "")
    ti = next(i for i, l in enumerate(lines) if l.startswith("| Vendor |"))
    te = max(i for i, l in enumerate(lines) if l.startswith("|"))
    return ts, counts, lines[ti:te + 1]

def lint_evidence(page, ledger):
    # Every "## Validated so far" bullet — **`driver` · lane(s)** — <tier> ... — must match the ledger.
    parts = page.split("## Validated so far", 1)
    if len(parts) < 2:
        return []
    section = parts[1].split("\n## ", 1)[0]
    drivers = ledger.get("drivers", {})
    problems = []
    for m in re.finditer(r'\*\*`([a-z0-9]+)`\s*·\s*(.+?)\*\*\s*[—-]+\s*(.+)', section):
        drv, lanes_s, rest = m.group(1), m.group(2), m.group(3)
        tm = re.search(r'\b(known-issue|hardware|emulation|spec)\b', rest)
        if not tm:
            problems.append(f"{drv} · {lanes_s}: no tier word found in the evidence line")
            continue
        tier = tm.group(1)
        for lane in [x.strip() for x in re.split(r'[/,]', lanes_s)]:
            got = ((drivers.get(drv, {}) or {}).get(lane, {}) or {}).get("status")
            if got != tier:
                problems.append(f"{drv} · {lane}: evidence claims '{tier}' but the ledger says '{got}'")
    return problems

def splice(page, ts, counts, table):
    lines = page.split("\n")
    region = [START, "",
              f"*Table + counts generated {ts} from the validation ledger via `SkansCP --driver-validation` — never hand-edited.*",
              "", counts, ""] + table + ["", END]
    if any(START in l for l in lines):
        si = next(i for i, l in enumerate(lines) if START in l)
        ei = next(i for i, l in enumerate(lines) if END in l)
    else:  # first run: replace the current counts line + table
        si = next(i for i, l in enumerate(lines) if l.startswith("**Cert-deploy ("))
        ei = max(i for i, l in enumerate(lines) if l.startswith("|"))
    return "\n".join(lines[:si] + region + lines[ei + 1:])

md = run_verb_and_fetch()
ledger = fetch_ledger()
ts, counts, table = extract(md)
page = open(PAGE, encoding="utf-8").read()

problems = lint_evidence(page, ledger)
if problems:
    print("LINT FAILED — the curated evidence claims a status the ledger does not back (fix the prose or run the test):")
    for p in problems:
        print("   -", p)
    sys.exit(1)

open(PAGE, "w", encoding="utf-8").write(splice(page, ts, counts, table))
print(f"synced OK — {len(table) - 2} driver rows + counts regenerated from the ledger; evidence lint passed ({ts})")
